import { SERVICE_MANIFEST, getServiceDependencies } from '../services';

/**
 * Generates a docker-compose.yml content based on selected services
 * Compatible with Homelab Media Server v5.0.0 architecture
 */
export const generateDockerComposeContent = (selectedServices, configValues, serviceManifest = SERVICE_MANIFEST) => {
  const domain = configValues.DOMAIN || 'example.com';
  const configPath = configValues.CONFIG_PATH || '/opt/homelab/config';
  const dataPath = configValues.DATA_PATH || '/opt/homelab/data';
  const mediaPath = configValues.MEDIA_PATH || '/opt/homelab/media';
  const downloadsPath = configValues.DOWNLOADS_PATH || '/opt/homelab/downloads';
  const uploadPath = configValues.UPLOAD_PATH || '/opt/homelab/uploads';

  // Collect all services including dependencies
  const allServices = new Set();
  selectedServices.forEach(serviceId => {
    const deps = getServiceDependencies(serviceId);
    deps.forEach(dep => allServices.add(dep));
  });

  // Build profiles from selected groups
  const profiles = new Set();
  allServices.forEach(serviceId => {
    const service = serviceManifest[serviceId];
    if (service && !service.always_on && !service.internal) {
      profiles.add(service.group);
    }
  });

  // Generate YAML content
  let yaml = `# =============================================================================
# HOMELAB MEDIA SERVER - Generated Configuration
# =============================================================================
# Generated by Homelab Configurator
# Documentation: https://github.com/BluuArtiis-FR/Homelab-Media-Server
# =============================================================================

networks:
  homelab:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
  traefik_public:
    name: traefik_public
    driver: bridge

x-common-env: &common-env
  PUID: \${PUID:-1000}
  PGID: \${PGID:-1000}
  TZ: \${TZ:-Europe/Paris}

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

x-healthcheck-defaults: &healthcheck-defaults
  interval: 30s
  timeout: 10s
  retries: 3
  start_period: 40s

volumes:
`;

  // Generate volumes
  const volumes = generateVolumes(allServices, serviceManifest);
  yaml += volumes;

  yaml += `
services:
`;

  // Generate services
  yaml += generateInfrastructureServices(configValues);

  allServices.forEach(serviceId => {
    const service = serviceManifest[serviceId];
    if (service && !service.always_on) {
      yaml += generateServiceYaml(serviceId, service, configValues);
    }
  });

  return yaml;
};

/**
 * Generate volumes section
 */
const generateVolumes = (services, manifest) => {
  const volumeMap = {
    'traefik': ['traefik_letsencrypt'],
    'authentik-server': ['authentik_postgres_data', 'authentik_redis_data'],
    'jellyfin': ['jellyfin_config', 'jellyfin_cache'],
    'jellyseerr': ['jellyseerr_config'],
    'tdarr': ['tdarr_config', 'tdarr_server'],
    'jellystat': ['jellystat_config'],
    'gluetun': ['gluetun_config'],
    'qbittorrent': ['qbittorrent_config'],
    'prowlarr': ['prowlarr_config'],
    'sonarr': ['sonarr_config'],
    'radarr': ['radarr_config'],
    'lidarr': ['lidarr_config'],
    'bazarr': ['bazarr_config'],
    'unpackerr': ['unpackerr_config'],
    'nextcloud': ['nextcloud_data', 'nextcloud_db_data'],
    'duplicati': ['duplicati_config', 'backup_data'],
    'filebrowser': ['filebrowser_config'],
    'onlyoffice': ['onlyoffice_data', 'onlyoffice_logs'],
    'stirling-pdf': ['stirlingpdf_config'],
    'jirafeau': ['jirafeau_data'],
    'bookstack': ['bookstack_config', 'bookstack_db_data'],
    'paperless-ngx': ['paperless_config', 'paperless_db_data', 'paperless_redis_data', 'paperless_consume'],
    'vaultwarden': ['vaultwarden_data'],
    'tailscale': ['tailscale_data'],
    'mealie': ['mealie_data'],
    'immich-server': ['immich_upload', 'immich_db_data', 'immich_redis_data', 'immich_ml_cache'],
    'firefly-iii': ['firefly_db_data'],
    'grocy': ['grocy_config'],
    'home-assistant': ['homeassistant_config'],
    'freshrss': ['freshrss_data'],
    'metube': ['metube_downloads'],
    'changedetection': ['changedetection_data'],
    'shlink': ['shlink_data', 'shlink_db_data'],
    'portainer': ['portainer_data'],
    'code-server': ['codeserver_config'],
    'dozzle': ['dozzle_data'],
    'adguardhome': ['adguardhome_work', 'adguardhome_conf'],
    'rustdesk-server': ['rustdesk_data'],
    'wger': ['wger_static', 'wger_media', 'wger_db_data'],
    'prometheus': ['prometheus_data'],
    'grafana': ['grafana_data'],
    'alertmanager': ['alertmanager_data']
  };

  let volumesYaml = '  # Infrastructure\n  traefik_letsencrypt:\n  authentik_postgres_data:\n  authentik_redis_data:\n';

  services.forEach(serviceId => {
    if (volumeMap[serviceId]) {
      volumeMap[serviceId].forEach(vol => {
        volumesYaml += `  ${vol}:\n`;
      });
    }
  });

  return volumesYaml;
};

/**
 * Generate infrastructure services (always on)
 */
const generateInfrastructureServices = (config) => {
  const domain = config.DOMAIN || 'example.com';
  const acmeEmail = config.ACME_EMAIL || 'admin@example.com';
  const configPath = config.CONFIG_PATH || '/opt/homelab/config';

  return `  # ===========================================================================
  # INFRASTRUCTURE - Always active
  # ===========================================================================

  traefik:
    image: traefik:v3.0
    container_name: traefik
    command:
      - "--api.dashboard=true"
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik_public"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=${acmeEmail}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--log.level=INFO"
      - "--ping=true"
      - "--metrics.prometheus=true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_letsencrypt:/letsencrypt
    networks:
      - traefik_public
      - homelab
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-dashboard.rule=Host(\`traefik.${domain}\`)"
      - "traefik.http.routers.traefik-dashboard.entrypoints=websecure"
      - "traefik.http.routers.traefik-dashboard.tls.certresolver=letsencrypt"
      - "traefik.http.routers.traefik-dashboard.service=api@internal"
      - "traefik.http.routers.traefik-dashboard.middlewares=authentik@docker,security-headers@docker"
      - "traefik.http.middlewares.security-headers.headers.stsSeconds=31536000"
      - "traefik.http.middlewares.security-headers.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.security-headers.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.security-headers.headers.browserXssFilter=true"
      - "traefik.http.middlewares.security-headers.headers.frameDeny=true"
    restart: unless-stopped
    logging: *default-logging
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      <<: *healthcheck-defaults

  authentik-postgres:
    image: postgres:15-alpine
    container_name: authentik-postgres
    environment:
      POSTGRES_PASSWORD: \${AUTHENTIK_PG_PASS}
      POSTGRES_USER: authentik
      POSTGRES_DB: authentik
    volumes:
      - authentik_postgres_data:/var/lib/postgresql/data
    networks:
      - homelab
    restart: unless-stopped
    logging: *default-logging
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U authentik"]
      <<: *healthcheck-defaults

  authentik-redis:
    image: redis:7-alpine
    container_name: authentik-redis
    command: --save 60 1 --loglevel warning
    volumes:
      - authentik_redis_data:/data
    networks:
      - homelab
    restart: unless-stopped
    logging: *default-logging
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      <<: *healthcheck-defaults

  authentik-server:
    image: ghcr.io/goauthentik/server:2024.2
    container_name: authentik-server
    command: server
    environment:
      AUTHENTIK_SECRET_KEY: \${AUTHENTIK_SECRET_KEY}
      AUTHENTIK_REDIS__HOST: authentik-redis
      AUTHENTIK_POSTGRESQL__HOST: authentik-postgres
      AUTHENTIK_POSTGRESQL__USER: authentik
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__PASSWORD: \${AUTHENTIK_PG_PASS}
    volumes:
      - ${configPath}/authentik/media:/media
      - ${configPath}/authentik/templates:/templates
    networks:
      - homelab
      - traefik_public
    depends_on:
      authentik-postgres:
        condition: service_healthy
      authentik-redis:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.authentik.rule=Host(\`auth.${domain}\`)"
      - "traefik.http.routers.authentik.entrypoints=websecure"
      - "traefik.http.routers.authentik.tls.certresolver=letsencrypt"
      - "traefik.http.services.authentik.loadbalancer.server.port=9000"
      - "traefik.http.middlewares.authentik.forwardauth.address=http://authentik-server:9000/outpost.goauthentik.io/auth/traefik"
      - "traefik.http.middlewares.authentik.forwardauth.trustForwardHeader=true"
      - "traefik.http.middlewares.authentik.forwardauth.authResponseHeaders=X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid"
    restart: unless-stopped
    logging: *default-logging
    healthcheck:
      test: ["CMD", "ak", "healthcheck"]
      <<: *healthcheck-defaults

  authentik-worker:
    image: ghcr.io/goauthentik/server:2024.2
    container_name: authentik-worker
    command: worker
    environment:
      AUTHENTIK_SECRET_KEY: \${AUTHENTIK_SECRET_KEY}
      AUTHENTIK_REDIS__HOST: authentik-redis
      AUTHENTIK_POSTGRESQL__HOST: authentik-postgres
      AUTHENTIK_POSTGRESQL__USER: authentik
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__PASSWORD: \${AUTHENTIK_PG_PASS}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${configPath}/authentik/media:/media
      - ${configPath}/authentik/certs:/certs
      - ${configPath}/authentik/templates:/templates
    networks:
      - homelab
    depends_on:
      authentik-postgres:
        condition: service_healthy
      authentik-redis:
        condition: service_healthy
    restart: unless-stopped
    logging: *default-logging

`;
};

/**
 * Generate YAML for a single service
 */
const generateServiceYaml = (serviceId, service, config) => {
  const domain = config.DOMAIN || 'example.com';
  const profile = service.group;
  const subdomain = service.subdomain || serviceId;

  // Service image mapping
  const imageMap = {
    'gluetun': 'qmcgaw/gluetun:latest',
    'qbittorrent': 'lscr.io/linuxserver/qbittorrent:latest',
    'prowlarr': 'lscr.io/linuxserver/prowlarr:latest',
    'sonarr': 'lscr.io/linuxserver/sonarr:latest',
    'radarr': 'lscr.io/linuxserver/radarr:latest',
    'lidarr': 'lscr.io/linuxserver/lidarr:latest',
    'bazarr': 'lscr.io/linuxserver/bazarr:latest',
    'unpackerr': 'golift/unpackerr:latest',
    'jellyfin': 'jellyfin/jellyfin:latest',
    'jellyseerr': 'fallenbagel/jellyseerr:latest',
    'tdarr': 'ghcr.io/haveagitgat/tdarr:latest',
    'jellystat': 'cyfershepard/jellystat:latest',
    'jellystat-db': 'postgres:15-alpine',
    'nextcloud': 'nextcloud:28-apache',
    'nextcloud-db': 'postgres:15-alpine',
    'nextcloud-redis': 'redis:7-alpine',
    'duplicati': 'lscr.io/linuxserver/duplicati:latest',
    'filebrowser': 'filebrowser/filebrowser:latest',
    'onlyoffice': 'onlyoffice/documentserver:latest',
    'stirling-pdf': 'frooodle/s-pdf:latest',
    'jirafeau': 'jgeusebroek/jirafeau:latest',
    'bookstack': 'lscr.io/linuxserver/bookstack:latest',
    'bookstack-db': 'mariadb:10.11',
    'paperless-ngx': 'ghcr.io/paperless-ngx/paperless-ngx:latest',
    'paperless-db': 'postgres:15-alpine',
    'paperless-redis': 'redis:7-alpine',
    'vaultwarden': 'vaultwarden/server:latest',
    'tailscale': 'tailscale/tailscale:stable',
    'mealie': 'ghcr.io/mealie-recipes/mealie:latest',
    'immich-server': 'ghcr.io/immich-app/immich-server:release',
    'immich-ml': 'ghcr.io/immich-app/immich-machine-learning:release',
    'immich-db': 'tensorchord/pgvecto-rs:pg14-v0.2.0',
    'immich-redis': 'redis:7-alpine',
    'firefly-iii': 'fireflyiii/core:latest',
    'firefly-db': 'postgres:15-alpine',
    'grocy': 'lscr.io/linuxserver/grocy:latest',
    'home-assistant': 'ghcr.io/home-assistant/home-assistant:stable',
    'freshrss': 'freshrss/freshrss:latest',
    'metube': 'ghcr.io/alexta69/metube:latest',
    'changedetection': 'ghcr.io/dgtlmoon/changedetection.io:latest',
    'changedetection-browser': 'browserless/chrome:latest',
    'shlink': 'shlinkio/shlink:stable',
    'shlink-db': 'postgres:15-alpine',
    'portainer': 'portainer/portainer-ce:latest',
    'code-server': 'lscr.io/linuxserver/code-server:latest',
    'dozzle': 'amir20/dozzle:latest',
    'adguardhome': 'adguard/adguardhome:latest',
    'rustdesk-server': 'rustdesk/rustdesk-server:latest',
    'rustdesk-relay': 'rustdesk/rustdesk-server:latest',
    'wger': 'wger/server:latest',
    'wger-db': 'postgres:15-alpine',
    'wger-redis': 'redis:7-alpine',
    'prometheus': 'prom/prometheus:latest',
    'grafana': 'grafana/grafana:latest',
    'alertmanager': 'prom/alertmanager:latest',
    'node-exporter': 'prom/node-exporter:latest',
    'cadvisor': 'gcr.io/cadvisor/cadvisor:latest'
  };

  const image = imageMap[serviceId] || `lscr.io/linuxserver/${serviceId}:latest`;

  let yaml = `  # ---------------------------------------------------------------------------
  # ${service.name}
  # ---------------------------------------------------------------------------
  ${serviceId}:
    image: ${image}
    container_name: ${serviceId}
    profiles: ["${profile}", "${serviceId}"]
`;

  // Add environment
  yaml += `    environment:
      <<: *common-env
`;

  // Add networks
  if (service.expose) {
    yaml += `    networks:
      - homelab
      - traefik_public
`;
  } else {
    yaml += `    networks:
      - homelab
`;
  }

  // Add Traefik labels for exposed services
  if (service.expose && !service.internal) {
    yaml += `    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${serviceId}.rule=Host(\`${subdomain}.${domain}\`)"
      - "traefik.http.routers.${serviceId}.entrypoints=websecure"
      - "traefik.http.routers.${serviceId}.tls.certresolver=letsencrypt"
      - "traefik.http.routers.${serviceId}.middlewares=authentik@docker,security-headers@docker"
      - "traefik.http.services.${serviceId}.loadbalancer.server.port=${service.port || 80}"
`;
  }

  yaml += `    restart: unless-stopped
    logging: *default-logging
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:${service.port || 80} || exit 1"]
      <<: *healthcheck-defaults

`;

  return yaml;
};

/**
 * Generate .env file content
 */
export const generateEnvContent = (configValues) => {
  let env = `# =============================================================================
# HOMELAB MEDIA SERVER - Environment Configuration
# Generated by Homelab Configurator
# =============================================================================

# -----------------------------------------------------------------------------
# GENERAL SETTINGS
# -----------------------------------------------------------------------------
PUID=${configValues.PUID || 1000}
PGID=${configValues.PGID || 1000}
TZ=${configValues.TZ || 'Europe/Paris'}
DOMAIN=${configValues.DOMAIN || 'example.com'}
ACME_EMAIL=${configValues.ACME_EMAIL || 'admin@example.com'}

# -----------------------------------------------------------------------------
# PATHS
# -----------------------------------------------------------------------------
CONFIG_PATH=${configValues.CONFIG_PATH || '/opt/homelab/config'}
DATA_PATH=${configValues.DATA_PATH || '/opt/homelab/data'}
MEDIA_PATH=${configValues.MEDIA_PATH || '/opt/homelab/media'}
DOWNLOADS_PATH=${configValues.DOWNLOADS_PATH || '/opt/homelab/downloads'}
UPLOAD_PATH=${configValues.UPLOAD_PATH || '/opt/homelab/uploads'}

# -----------------------------------------------------------------------------
# AUTHENTIK (SSO)
# -----------------------------------------------------------------------------
AUTHENTIK_SECRET_KEY=${configValues.AUTHENTIK_SECRET_KEY || '# Generate with: openssl rand -base64 50'}
AUTHENTIK_PG_PASS=${configValues.AUTHENTIK_PG_PASS || '# Generate with: openssl rand -base64 32'}

`;

  // Add VPN config if download services are selected
  if (configValues.VPN_SERVICE_PROVIDER) {
    env += `# -----------------------------------------------------------------------------
# VPN (GLUETUN)
# -----------------------------------------------------------------------------
VPN_SERVICE_PROVIDER=${configValues.VPN_SERVICE_PROVIDER}
VPN_TYPE=${configValues.VPN_TYPE || 'openvpn'}
OPENVPN_USER=${configValues.OPENVPN_USER || ''}
OPENVPN_PASSWORD=${configValues.OPENVPN_PASSWORD || ''}
SERVER_COUNTRIES=${configValues.SERVER_COUNTRIES || 'Switzerland'}

`;
  }

  // Add other secrets based on selected services
  const secretFields = [
    'NEXTCLOUD_ADMIN_PASS', 'NEXTCLOUD_DB_PASS',
    'BOOKSTACK_DB_PASS', 'PAPERLESS_SECRET_KEY', 'PAPERLESS_DB_PASS', 'PAPERLESS_ADMIN_PASS',
    'ONLYOFFICE_JWT_SECRET', 'IMMICH_DB_PASS',
    'FIREFLY_APP_KEY', 'FIREFLY_DB_PASS',
    'WGER_SECRET_KEY', 'WGER_DB_PASS',
    'SHLINK_DB_PASS', 'SHLINK_API_KEY',
    'CODESERVER_PASSWORD', 'GRAFANA_ADMIN_PASS',
    'JELLYSTAT_DB_PASS', 'JELLYSTAT_JWT_SECRET'
  ];

  env += `# -----------------------------------------------------------------------------
# SERVICE SECRETS
# -----------------------------------------------------------------------------
`;
  secretFields.forEach(field => {
    if (configValues[field]) {
      env += `${field}=${configValues[field]}\n`;
    }
  });

  return env;
};

/**
 * Generate profiles list for docker compose command
 */
export const generateProfilesCommand = (selectedServices, manifest = SERVICE_MANIFEST) => {
  const profiles = new Set();
  selectedServices.forEach(serviceId => {
    const service = manifest[serviceId];
    if (service && !service.always_on && service.group) {
      profiles.add(service.group);
    }
  });

  if (profiles.size === 0) return 'docker compose up -d';

  const profileArgs = Array.from(profiles).map(p => `--profile ${p}`).join(' ');
  return `docker compose ${profileArgs} up -d`;
};
